export const BUILD_SM_UI = 'BUILD_SM_UI';
export const REBUILD_SM_UI = 'REBUILD_SM_UI';
export const DELETE_ITEM = 'DELETE_ITEM';

export const ADD_DROP_TARGETS = 'ADD_DROP_TARGETS';
export const REMOVE_DROP_TARGETS = 'REMOVE_DROP_TARGETS';
export const SET_ACTIVE_DRAG_SOURCE = 'SET_ACTIVE_DRAG_SOURCE';
export const REMOVE_ACTIVE_DRAG_SOURCES = 'REMOVE_ACTIVE_DRAG_SOURCES';
export const HANDLE_LIST_ITEM_DROP = 'HANDLE_LIST_ITEM_DROP';

export const IS_EDITING_TIMESPAN = 'IS_EDITING_TIMESPAN';
export const RETRIEVE_STRUCTURE_SUCCESS = 'RETRIEVE_STRUCTURE_SUCCESS';
export const UPDATE_STRUCTURE_STATUS = 'UPDATE_STRUCTURE_STATUS';
export const HANDLE_STRUCTURE_ERROR = 'HANDLE_STRUCTURE_ERROR';
export const RETRIEVE_WAVEFORM_SUCCESS = 'RETRIEVE_WAVEFORM_SUCCESS';
export const SAVE_INIT_SMDATA = 'SAVE_INIT_SMDATA';

export const STREAM_MEDIA_ERROR = 'STREAM_MEDIA_ERROR';
export const STREAM_MEDIA_SUCCESS = 'STREAM_MEDIA_SUCCESS';

export const INIT_PEAKS = 'INIT_PEAKS';
export const PEAKS_READY = 'PEAKS_READY';
export const INSERT_SEGMENT = 'INSERT_SEGMENT';
export const DELETE_SEGMENT = 'DELETE_SEGMENT';
export const ACTIVATE_SEGMENT = 'ACTIVATE_SEGMENT';
export const INSERT_PLACEHOLDER = 'INSERT_PLACEHOLDER';
export const SAVE_SEGMENT = 'SAVE_SEGMENT';
export const REVERT_SEGMENT = 'REVERT_SEGMENT';
export const UPDATE_SEGMENT = 'UPDATE_SEGMENT';
export const TEMP_INSERT_SEGMENT = 'TEMP_INSERT_SEGMENT';
export const TEMP_DELETE_SEGMENT = 'TEMP_DELETE_SEGMENT';
export const IS_DRAGGING = 'IS_DRAGGING';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const CLEAR_EXISTING_ALERTS = 'CLEAR_EXISTING_ALERTS';

export const RESET_STORE = 'RESET_STORE';
export const SET_MANIFEST = 'SET_MANIFEST';
export const FETCH_MANIFEST_ERROR = 'FETCH_MANIFEST_ERROR';
export const FETCH_MANIFEST_SUCCESS = 'FETCH_MANIFEST_SUCCESS';
export const PARSE_MANIFEST_STRUCTURE = 'PARSE_MANIFEST_STRUCTURE';
export const SET_MANIFEST_MEDIAINFO = 'SET_MANIFEST_MEDIAINFO';