export const ADD_HEADING = 'ADD_HEADING';
export const EDIT_HEADING = 'EDIT_HEADING';
export const ADD_TIME_SPAN = 'ADD_TIME_SPAN';
export const EDIT_TIME_SPAN = 'EDIT_TIME_SPAN';
export const BUILD_SM_UI = 'BUILD_SM_UI';

export const DELETE_ITEM = 'DELETE_ITEM';

export const ADD_DROP_TARGETS = 'ADD_DROP_TARGETS';
export const REMOVE_DROP_TARGETS = 'REMOVE_DROP_TARGETS';
export const SET_ACTIVE_DRAG_SOURCE = 'SET_ACTIVE_DRAG_SOURCE';
export const REMOVE_ACTIVE_DRAG_SOURCES = 'REMOVE_ACTIVE_DRAG_SOURCES';
export const HANDLE_LIST_ITEM_DROP = 'HANDLE_LIST_ITEM_DROP';

export const IS_EDITING_TIMESPAN = 'IS_EDITING_TIMESPAN';
export const RETRIEVED_WAVEFORM = 'RETRIEVED_WAVEFORM';
export const RETRIEVED_STRUCTURE = 'RETRIEVED_STRUCTURE';

export const INIT_PEAKS = 'INIT_PEAKS';
export const INSERT_SEGMENT = 'INSERT_SEGMENT';
export const DELETE_SEGMENT = 'DELETE_SEGMENT';
export const ACTIVATE_SEGMENT = 'ACTIVATE_SEGMENT';
export const SAVE_SEGMENT = 'SAVE_SEGMENT';
export const REVERT_SEGMENT = 'REVERT_SEGMENT';
export const UPDATE_SEGMENT = 'UPDATE_SEGMENT';
export const DRAG_SEGMENT = 'DRAG_SEGMENT';

export const TEMP_INSERT_SEGMENT = 'TEMP_INSERT_SEGMENT';
export const TEMP_DELETE_SEGMENT = 'TEMP_DELETE_SEGMENT';
