'use strict';

exports.__esModule = true;
var ADD_HEADING = exports.ADD_HEADING = 'ADD_HEADING';
var EDIT_HEADING = exports.EDIT_HEADING = 'EDIT_HEADING';
var ADD_TIME_SPAN = exports.ADD_TIME_SPAN = 'ADD_TIME_SPAN';
var EDIT_TIME_SPAN = exports.EDIT_TIME_SPAN = 'EDIT_TIME_SPAN';
var BUILD_SM_UI = exports.BUILD_SM_UI = 'BUILD_SM_UI';

var DELETE_ITEM = exports.DELETE_ITEM = 'DELETE_ITEM';

var ADD_DROP_TARGETS = exports.ADD_DROP_TARGETS = 'ADD_DROP_TARGETS';
var REMOVE_DROP_TARGETS = exports.REMOVE_DROP_TARGETS = 'REMOVE_DROP_TARGETS';
var SET_ACTIVE_DRAG_SOURCE = exports.SET_ACTIVE_DRAG_SOURCE = 'SET_ACTIVE_DRAG_SOURCE';
var REMOVE_ACTIVE_DRAG_SOURCES = exports.REMOVE_ACTIVE_DRAG_SOURCES = 'REMOVE_ACTIVE_DRAG_SOURCES';
var HANDLE_LIST_ITEM_DROP = exports.HANDLE_LIST_ITEM_DROP = 'HANDLE_LIST_ITEM_DROP';

var IS_EDITING_TIMESPAN = exports.IS_EDITING_TIMESPAN = 'IS_EDITING_TIMESPAN';
var RETRIEVED_WAVEFORM = exports.RETRIEVED_WAVEFORM = 'RETRIEVED_WAVEFORM';
var RETRIEVED_STRUCTURE = exports.RETRIEVED_STRUCTURE = 'RETRIEVED_STRUCTURE';

var INIT_PEAKS = exports.INIT_PEAKS = 'INIT_PEAKS';
var INSERT_SEGMENT = exports.INSERT_SEGMENT = 'INSERT_SEGMENT';
var DELETE_SEGMENT = exports.DELETE_SEGMENT = 'DELETE_SEGMENT';
var ACTIVATE_SEGMENT = exports.ACTIVATE_SEGMENT = 'ACTIVATE_SEGMENT';
var SAVE_SEGMENT = exports.SAVE_SEGMENT = 'SAVE_SEGMENT';
var REVERT_SEGMENT = exports.REVERT_SEGMENT = 'REVERT_SEGMENT';
var UPDATE_SEGMENT = exports.UPDATE_SEGMENT = 'UPDATE_SEGMENT';
var DRAG_SEGMENT = exports.DRAG_SEGMENT = 'DRAG_SEGMENT';

var TEMP_INSERT_SEGMENT = exports.TEMP_INSERT_SEGMENT = 'TEMP_INSERT_SEGMENT';
var TEMP_DELETE_SEGMENT = exports.TEMP_DELETE_SEGMENT = 'TEMP_DELETE_SEGMENT';