export var ADD_HEADING = 'ADD_HEADING';
export var EDIT_HEADING = 'EDIT_HEADING';
export var ADD_TIME_SPAN = 'ADD_TIME_SPAN';
export var EDIT_TIME_SPAN = 'EDIT_TIME_SPAN';
export var BUILD_SM_UI = 'BUILD_SM_UI';

export var DELETE_ITEM = 'DELETE_ITEM';

export var ADD_DROP_TARGETS = 'ADD_DROP_TARGETS';
export var REMOVE_DROP_TARGETS = 'REMOVE_DROP_TARGETS';
export var SET_ACTIVE_DRAG_SOURCE = 'SET_ACTIVE_DRAG_SOURCE';
export var REMOVE_ACTIVE_DRAG_SOURCES = 'REMOVE_ACTIVE_DRAG_SOURCES';
export var HANDLE_LIST_ITEM_DROP = 'HANDLE_LIST_ITEM_DROP';

export var IS_EDITING_TIMESPAN = 'IS_EDITING_TIMESPAN';
export var RETRIEVED_WAVEFORM = 'RETRIEVED_WAVEFORM';
export var RETRIEVED_STRUCTURE = 'RETRIEVED_STRUCTURE';

export var INIT_PEAKS = 'INIT_PEAKS';
export var INSERT_SEGMENT = 'INSERT_SEGMENT';
export var DELETE_SEGMENT = 'DELETE_SEGMENT';
export var ACTIVATE_SEGMENT = 'ACTIVATE_SEGMENT';
export var SAVE_SEGMENT = 'SAVE_SEGMENT';
export var REVERT_SEGMENT = 'REVERT_SEGMENT';
export var UPDATE_SEGMENT = 'UPDATE_SEGMENT';
export var DRAG_SEGMENT = 'DRAG_SEGMENT';

export var TEMP_INSERT_SEGMENT = 'TEMP_INSERT_SEGMENT';
export var TEMP_DELETE_SEGMENT = 'TEMP_DELETE_SEGMENT';